// export { default as houseImg } from './house1.png'
// export { default as restaurantImg } from './restaurant.png'
// export { default as casinoImg } from './casino.png'
export { default as parkImg } from './park.png'
// export { default as schoolImg } from './school.png'
// export { default as storeImg } from './store.png'
// export { default as hospitalImg } from './hospital.png'

export { default as moneyImg } from './money.png'
export { default as flashImg } from './flash.png'

export { default as monsterImage } from './monster.png'
export { default as creatureImage } from './creature.png'

export { default as bgImage1 } from './bg1.jpg'
export { default as bgImage2 } from './bg2.jpg'
export { default as bgImage3 } from './bg3.jpg'
export { default as bgImage4 } from './bg4.jpg'
export { default as bgImage5 } from './bg5.jpg'
export { default as bgImage6 } from './bg6.jpg'
