export { default as correctSound } from './correct.mp3'
export { default as wrongSound } from './wrong.mp3'
export { default as pressSound } from './press.mp3'
export { default as startSound } from './start.mp3'
export { default as attackSound } from './attack.mp3'
